#+title: README

Jai bindings for SDL3. Work in progress.

In this branch I have attempted to modify the standard bindings to make them easier to work with in Jai programgs:
- Remove SDL_ prefix from all bindings, so module can be imported into an SDL namespace if desired without an ugly duplicated prefix.
- snake_case for all function calls.
- All numeric constants that otherwise behave like enums are now just enums/enum flags. This removes the guesswork when deciding whether or not the unary dot syntax should be used for a particular flag.

* SDL3 source
- https://github.com/libsdl-org/SDL/tree/main/include/SDL3

SDL3 build commands:
#+begin_src
git clone https://github.com/libsdl-org/SDL
cd SDL
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DSDL_STATIC=ON ..
cmake --build . --config Release --parallel
#+end_src

SDL_image build commands (assuming SDL and SDL_image root are at same directory level):
#+begin_src
git clone https://github.com/libsdl-org/SDL
cd SDL
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DSDL3_DIR=../SDL/build -DBUILD_SHARED_LIBS=ON
cmake --build . --config Release
cmake .. -DCMAKE_BUILD_TYPE=Release -DSDL3_DIR=../SDL/build -DBUILD_SHARED_LIBS=OFF
cmake --build . --config Release
#+end_src

* Finished
- SDL_platform.jai
- SDL_video.jai
- SDL_events.jai
- SDL_init.jai
- SDL_gpu.jai
- SDL_surface.jai
- SDL_rect.jai
- SDL_render.jai
- SDL_camera.jai
- SDL_touch.jai
- SDL_joystick.jai
- SDL_audio.jai
- SDL_pen.jai
- SDL_sensor.jai
- SDL_pixels.jai
- SDL_stdinc.jai
- SDL_properties.jai
- SDL_timer.jai
- SDL_power.jai
- SDL_error.jai
- SDL_scancode.jai
- SDL_mouse.jai
- SDL_keyboard.jai
- SDL_filesystem.jai
- SDL_iostream.jai
- SDL_blendmode.jai
- SDL_keycode.jai

* Unfinished
- SDL_image.jai
